language: java

services:
  - docker

script:
  - export SONAR_SCANNER_VERSION=$(cat ./VERSION)
  - echo ${SONAR_SCANNER_VERSION}
  - docker build --tag elnebuloso/sonarqube-scanner --pull --rm --no-cache --build-arg SONAR_SCANNER_VERSION=${SONAR_SCANNER_VERSION} --file Dockerfile .